---
# See https://www.gitpod.io/docs/config-gitpod-file

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-maven

tasks:
  - init: ./gradlew build
  - command: ./test.sh
